site_name: TOLIMAN
docs_dir: .
extra_css:
    - extra.css

plugins:
    - search
    - same-dir
    - simple
    - mkdocstrings:
        default_handler: python 

theme: 
    name: material 
    logo: toliman/assets/logo.png
