site_name: TOLIMAN
docs_dir: .

plugins:
  - search
  - same-dir
  - simple:
      include_folders: 
        - toliman
        - examples
      ignore_folders:
        - tests
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: "numpy"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

theme: 
  name: material 
  palette:
    scheme: default
    primary: blue
    accent: light blue
