site_name: TOLIMAN
docs_dir: .
plugins:
- search
- same-dir
#    - simple
- mkdocstrings:
    handlers: 
        python:
            options:
                docstring_style: numpy
                inherited_members: True

