site_name: TOLIMAN
docs_dir: .

plugins:
    - search
    - same-dir
    - simple
    - mkdocstrings

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences

theme: 
    name: material 
    palette:
        scheme: default
        primary: blue
        accent: light blue
