[tool.poetry]
name = "toliman"
description = "A differential model of TOLIMAN telescope."
version = "0.0.1"
authors = [
    {name = "Jordan Dennis", email = "jdenn105@gmail.com"},
    {name = "Conaire Deagan"},
    {name = "Louis Desdoigts"}
]
readme = "README.md"
packages = [{include = "poetry_demo"}]

[tool.poetry.dependencies]
python = "^3.7"
jax = "0.4.1"
dLux = "0.1.2"
pysynphot = "2.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"[project]

